### ISSUE TITLE
Fully document the build and release process

### ISSUE THREAD

**Issue by jessebraham** [esp-rs/rust-build#134]
We should have some document, whether it's in this repo's wiki or just in a markdown file, which fully describes the process of building and releasing a new compiler in a way that anybody can understand and follow.

**Comment by georgik** [comment]
Added initial version of the document: https://github.com/esp-rs/rust-build/wiki/Build-and-release-process

@SergioGasquez Please add the part about building containers after toolchain release.

**Comment by SergioGasquez** [comment]
Just added [`Uploading new image tags to espressif/idf-rust`](https://github.com/esp-rs/rust-build/wiki/Build-and-release-process#uploading-new-image-tags-to-espressifidf-rust) section.
