### ISSUE TITLE
Use Ubuntu 18.04 to build release assets

### ISSUE THREAD

**Issue by lexxvir** [esp-rs/rust-build#167]
Hello,

Is it possible to build & release linux artifacts that are compatible with Ubuntu 18.04 ?

I have tried 1.65.0.0 release on Ubuntu 18.04 and got error that GLIBC version is too old:
```
$ tar xf rust-1.65.0.0-x86_64-unknown-linux-gnu.tar.xz
$ cd rust-nightly-x86_64-unknown-linux-gnu
$ ./cargo/bin/cargo 
./cargo/bin/cargo: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./cargo/bin/cargo)
./cargo/bin/cargo: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by ./cargo/bin/cargo)
./cargo/bin/cargo: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./cargo/bin/cargo)
```

I checked rust-1.65.0.0-x86_64-unknown-linux-gnu.tar.xz.

**Comment by SergioGasquez** [comment]
Hi!

> Is it possible to build & release linux artifacts that are compatible with Ubuntu 18.04 ?

We decided not to release artifacts for Ubtuntu 18.04 as it coming to its [end of life soon](https://wiki.ubuntu.com/Releases)

I would suggest trying: https://stackoverflow.com/questions/72513993/how-install-glibc-2-29-or-higher-in-ubuntu-18-04
