### ISSUE TITLE
Cannot find clippy and rustfmt in bin directory of Windows build

### ISSUE THREAD

**Issue by chang196700** [esp-rs/rust-build#178]

**Comment by georgik** [comment]
@chang196700 Please, could you provide information which deployment method was used?

I've noticed the problem in case of using espup. PowerShell scripts seems to work without problem, please try the deployment by PowerShell: https://github.com/esp-rs/rust-build/releases

**Comment by chang196700** [comment]
Download the zip file from https://github.com/esp-rs/rust-build/releases/download/v1.66.0.0/rust-1.66.0.0-x86_64-pc-windows-msvc.zip. There are no `cargo-clippy.exe`, `clippy-driver.exe` and `rustfmt.exe` files in the `esp/bin` directory
