### ISSUE TITLE
Windows: Copy `cargo.exe` into the `esp/bin` toolchain folder

### ISSUE THREAD

**Issue by SergioGasquez** [esp-rs/rust-build#186]
Some `espup` (https://github.com/esp-rs/espup/issues/85) were encountering the following issue: https://github.com/rust-lang/rustup/issues/2889.

[The fix is pretty straightforward, copy `cargo.exe` from the nightly toolchain to the `esp/bin/` folder](https://github.com/rust-lang/rustup/issues/2889#issuecomment-986216050). I've implemented this fix in `espup`: https://github.com/esp-rs/espup/pull/145, but I think it would be better to fix this here as it would fix it from the root cause and it would also solve it for the powershell script

**Comment by georgik** [comment]
Added cargo.exe, clippy and rustfmt to esp ZIP archive in 1.67.0.0
