### ISSUE TITLE
float to decimal conversion panic

### ISSUE THREAD

**Issue by farbodpm** [esp-rs/rust-build#189]
I face this error when working with float numbers

assertion failed: buf[0] > b\'0\'', /root/.rustup/toolchains/esp/lib/rustlib/src/rust/library/core/src/num/flt2dec/mod.rs:189:5

**Comment by MabezDev** [comment]
What version of the toolchain are you running?

**Comment by farbodpm** [comment]
ARG TOOLCHAIN_VERSION=1.63.0.2

**Comment by MabezDev** [comment]
That toolchain is very old, please update to the latest. This was fixed in 1.65 I believe.
