### ISSUE TITLE
Remove docker tag espressif/idf-rust:latest

### ISSUE THREAD

**Issue by georgik** [esp-rs/rust-build#200]
The image `espressif/idf-rust:last` is obsolete and was replaced by other tags, since they're more specific.

Suggested options: Either remove the tag or point the tag to `all`.

What is your opinion @SergioGasquez ?

**Comment by SergioGasquez** [comment]
I would suggest deleting the [`idf-rust:latest` tag](https://hub.docker.com/layers/espressif/idf-rust/latest/images/sha256-5094633ebd8e5842d61d69c3fc140dcaf2389e6bf7abf5f464d98bc185e1bab8?context=repo)

**Comment by SergioGasquez** [comment]
Tag deleted!
