### ISSUE TITLE
cargo build error

### ISSUE THREAD

**Issue by cmehmet** [esp-rs/rust-build#218]
This is the first error i get;;;
error: in C:\blink\rust-toolchain.toml: invalid toolchain name: 'esp'

After that i change the toolchain name esp to stable in that path C:\blink\rust-toolchain.toml but i get second error like the below;;;

error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names --target xtensa-esp32-espidf --crate-type bin 
--crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=split-debuginfo --print=crate-name --print=cfg` (exit code: 1)
  --- stderr
  error: Error loading target specification: Could not find specification for target "xtensa-esp32-espidf". Run `rustc --print 
target-list` for a list of built-in targets

<img width="964" alt="error1" src="https://github.com/esp-rs/rust-build/assets/75099404/92e93cd5-f851-4f8f-8a66-400ac9ef1be3">

<img width="961" alt="error2" src="https://github.com/esp-rs/rust-build/assets/75099404/53be4dd3-49ef-4b70-8ab6-450b9d34e10d">

I am grateful for any kind of help

**Comment by MabezDev** [comment]
The Xtensa enabled toolchain is not installed, please follow the instructions outlined in the book: https://esp-rs.github.io/book/.

**Comment by cmehmet** [comment]
Thank you so much for help
