### ISSUE TITLE
Add install-rust-toolchain.sh to release artifacts

### ISSUE THREAD

**Issue by rgcottrell** [esp-rs/rust-build#24]
I think it would be helpful to add the install-rust-toolchain.sh installer script to the release artifacts. This would make it easier to automate the process of installing the binary toolchains by simply downloading and then running the installer script. This would allow individual users to install the toolchain without needing to check out the source repository first.

**Comment by MabezDev** [comment]
@georgik this seems doable, we should just be able to append to the tar archive that `x.py dist` gives us? I don't know if that would mess up any signing or verification (if we do any at the moment) though.

**Comment by georgik** [comment]
That's great idea. 👍

**Comment by georgik** [comment]
Added .sh and .ps1.
