### ISSUE TITLE
Update rustc build with recently releases LLVM 13

### ISSUE THREAD

**Issue by lexxvir** [esp-rs/rust-build#25]
Hello,

Could you please issue a new release of the Rust toolchain that built upon recently released Espressif's LLVM 13?

Thank you.

**Comment by georgik** [comment]
Thank you @lexxvir . Scheduled for build 1.57.0.2

**Comment by georgik** [comment]
Build 1.57.0.2 is ready. 
Please test with installation scripts from build/1.57 branch: https://github.com/esp-rs/rust-build/tree/build/1.57

**Comment by georgik** [comment]
Solved in version 1.57.0.2
