### ISSUE TITLE
Target not found issue in mac.

### ISSUE THREAD

**Issue by Bulalu** [esp-rs/rust-build#257]
hi all,
I'm trying to compile an esp template after following all the steps on the esp book.
I'm using a mac with an m2 chip

<img width="714" alt="Screenshot 2024-03-04 at 00 13 37" src="https://github.com/esp-rs/rust-build/assets/71330824/4007fbe7-cd38-482f-8009-58f680b9716e">

**Comment by SergioGasquez** [comment]
Hi! See https://github.com/esp-rs/rust-build/issues/228#issuecomment-1975949228
