### ISSUE TITLE
`install-rust-toolchain.sh` bundled with tag 1.57.0.2 installs version 1.57.0.0

### ISSUE THREAD

**Issue by bugadani** [esp-rs/rust-build#26]
I see this has been fixed, but the last release still uses an older version of the install script, so I can't install the toolchain from a tag on CI, which is not that elegant :)

**Comment by georgik** [comment]
Thanks for reporting the problem. The relevant version of the script is also part of Releases.
Also it's possible to explicitly specify the version as a parameter to install script using `--toolchain-version` parameter.
The shifted tag is confusing. We should consider how to handle the situation for 1.58. 

BTW: @bugadani  Which CI do you use? Are you considering also Podman/Docker image idf-rust or idf-rust-examples? In case of GitHub there is also GitHub action which is able to use these images.

**Comment by bugadani** [comment]
I'm using GitHub actions, but a custom script because either there was no action yet when I started it, or I couldn't discover it very well. I'll take a look on what's available now.
