### ISSUE TITLE
Freeze when loading project

### ISSUE THREAD

**Issue by aliakseika** [esp-rs/rust-build#263]
Hello, when I try to load a project from the no_std template onto the device, esp just freezes for a moment, as in the screenshot and that’s it, no action happens. Tried it on esp32H2 and esp32C6. 
Maybe there are some ideas on what can be done about this?
<img width="805" alt="Снимок экрана 2024-04-04 в 18 33 32" src="https://github.com/esp-rs/rust-build/assets/122928641/a76f452b-cf7b-4890-9322-b9f1a893f5c3">

**Comment by SergioGasquez** [comment]
Sorry, what do you mean by "freezes"? That "Hello World" prints are not shown? Are those printed afterward?

**Comment by aliakseika** [comment]
No - these are the last lines after loading and this continues endlessly. 
I apologize, perhaps I am not expressing myself clearly. The fact is that I am writing through Google translator

**Comment by SergioGasquez** [comment]
Which devkit are you using? Are you using the "USB" or "UART" port of the devkit? Make sure you use the "UART" one

**Comment by aliakseika** [comment]
if i use uart port then i get different error
<img width="764" alt="Снимок экрана 2024-04-05 в 13 12 59" src="https://github.com/esp-rs/rust-build/assets/122928641/7204ad2f-8f86-42ef-a62b-4a6ca9548f2f">

**Comment by aliakseika** [comment]
it works, thanks 👍 )

**Comment by aliakseika** [comment]
maybe you also know how to set up debug in clion in this project? :)

**Comment by SergioGasquez** [comment]
> But then the firmware does not work

Firmware does work, but in the default example you are writing to UART, so if you connect to USB you dont receive it. Have a look at https://github.com/esp-rs/esp-hal/blob/main/examples/src/bin/usb_serial_jtag.rs
