### ISSUE TITLE
Anyway to prevent the docker images from doing a git clone?

### ISSUE THREAD

**Issue by jdfreder** [esp-rs/rust-build#271]
Hi ESP Rust community,

I noticed that when I build a hello world project (e.g. something generate from one of the cargo generate rust esp templates), that the build fetches content from a git repository somewhere. I was hoping I could have a hermetic build, but I'm not sure whether that's possible. Unfortunately the git clone from the internet causes the build to fail sporadically, as seen below:

<img width="1322" alt="image" src="https://github.com/user-attachments/assets/844d58b6-c589-4003-8821-9f3dbeaea32a">

Is there a recommended way to have a fully offline hermetic build using one of the docker images?

Best,
Jon

**Comment by SergioGasquez** [comment]
Hi!

I assume you are using `esp-idf-template`, which uses the std approach (see https://docs.esp-rs.org/book/overview/index.html), if you use `esp-template` (no_std approach) you won't need to clone anything.

Any std project, requires ESP-IDF source code (which is what your git clone is getting), either you let `esp-idf-sys` clone it and install it for you, or you can do it manually and [configure your project to use it](https://github.com/esp-rs/esp-idf-sys/blob/master/BUILD-OPTIONS.md#esp_idf_tools_install_dir-esp_idf_tools_install_dir). 

For questions, I would recommend using the [Matrix channel](https://matrix.to/#/#esp-rs:matrix.org)
