### ISSUE TITLE
Update of custom toolchain using rustup

### ISSUE THREAD

**Issue by georgik** [esp-rs/rust-build#51]
Scenario: User deployed toolchain 1.56.0.0 and later on user wants upgrade to 1.59.0.0
The installation script does not display any warning an quits.

Workaround:
- run installation with parameter `-i`: `./install-rust-toolchain.sh -i reinstall`
- or delete ~/.rustup/toolchains/esp

Expected behavior: Installer allows updated of the toolchain in the similar way like rustup

**Comment by stappersg** [comment]
> Expected behavior: Installer allows updated of the toolchain in the similar way like rustup

Thing I would like to know: Where is _merge with upstream `rustup`_ being tracked?

**Comment by georgik** [comment]
@stappersg There is an open request for "custom channels" for rustup. That would solve the problem: https://github.com/rust-lang/rustup/issues/2696

**Comment by georgik** [comment]
It does not seems lilely to fix this limitation. Closing the issue.
