### ISSUE TITLE
Research dependency of toolchains nightly and stable

### ISSUE THREAD

**Issue by georgik** [esp-rs/rust-build#72]
Right now we deploy stable, nightly and our toolchain for building ESP32 target.
Investigate, whether this is really necessary and whether the build can work even without nightly and stable.
Verify changes by running `test-rust-installer.sh`.

**Comment by georgik** [comment]
Research also whether it's possible to remove nightly and stable for ESP32C3

**Comment by SergioGasquez** [comment]
If we end up needing `nightly` and `stable` toolchains, we should also investigate using `--profile minimal`.
