### ISSUE TITLE
Remove PIP_USER="yes"

### ISSUE THREAD

**Issue by georgik** [esp-rs/rust-build#95]
Remove workaround `PIP_USER="yes"`, because solution is now part of ESP-IDF:
https://github.com/espressif/esp-idf/issues/7910

This environment variable was set on GitPod build machines and it was not possible to bootstrap the environment for ESP-IDF. The solution was applied to all release branches of ESP-IDF.

**Comment by svenstaro** [comment]
Shouldn't this be closed now with #96 merged?
